### PR TITLE
cmd: improve help wording for ECE specific commands

### PR DESCRIPTION
**Pull request by karencfv**
## Description
Adds "(for ECE installations only)" to the descriptions of the commands which are ECE-specific.

Concerns were raised about hiding commands based on host address, our documentation, the fact that our code is open sourced so users will be able to see our commands anyway and may wonder why they cannot see them. 

Modifying 401 error messages to be ESS specific also brings in a fair bit of complexity.

I believe that in order to avoid complexity and still provide a good UX, the best course of action is to let the users know which commands will only work in ECE through the --help flag, and the documentation. Users will receive a 401 error if they attempt to run this command.

## Related Issues
Closes: https://github.com/elastic/ecctl/issues/160

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation

## Readiness Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by zanbel** [comment]
After discussing today with @Kushmaro wanted to share my $.02 although I see the PR is merged but still maybe something to consider. The indication added about specific endpoint only being relevant for ECE are a bug, IMO. It's not accurate to say `(for ECE installations only)` since the commands are relevant for both ESS and ECE but require certain permissions. If we follow the same logic we should add indication for user with deployments manager or viewer roles about certain endpoints being `for platform admins only`.

My suggestion will be to let the API return a 403 in case the api key presented does not have enough permissions. And one more point about UI vs. API/CLI, in the user console we have an active session, meaning we can more easily customize the experience based on the authentication presented by the user. In API/CLI it's harder to assume that. Specifically with ecctl if API key is configured in the ecctl.config we can potentially try to fetch this information before every command by I have not seen this happened in similar tools. if there is an example of such practice I'll be happy to see it.

@Kushmaro @ppapapetrou76 @marclop @karencfv -- I'm happy to assist in a design discussion.

// cc @elastic/cloud-pms if folks might have other opinions or saw different examples

**Comment by karencfv** [comment]
@zanbel you make a very good point about the different roles. I'm perfectly fine with removing the extra text added in this PR, and letting the API return a 403. It would also be a good idea to mention this in our documentation.

About fetching roles from the user before every command, even though it's possible, I don't think it's a course of action we should pursue. Making another API call before every command would not only make the CLI slower, but would IMO add unnecessary complexity to our code.

**Comment by marclop** [comment]
Thanks for chiming in Roy, I think something along the lines of: `(Requires platform administration privileges)` might be a bit more precise, we can certainly change the working here if you're happy with that.

I'm also of the opinion that adding 1 extra API call can make the CLI seem slower than necessary since it would become an API call which needs to get made before the real command execution begins, that would require us to retrieve the permissions which the user has and hide or show specific parts of the help prompt. I think that adds a certain complexity which I'm not sure it's worth investing on now.

Regardless of the help text, the API will return a 403 (Maybe even a 404) if the user doesn't have the appropriate permissions to access those endpoints.

I have not seen other projects dynamically adjusting their help like you say, but it's something we might be able to do, but it can slow down the user's experience.

One thing we might want to do if we decided to go the route of fetching the API key's information and tied roles is to cache that information in the filesystem (with the checksum of the APIKey to make sure we don't return outdated information to the user if the APIKey changes) to reduce the cost of making an API call. This however will further increase the complexity of that workflow.

**Comment by karencfv** [comment]
Thanks for expanding on that Marc :) I like the text you propose.

I'd also like to add that if we decided to go with the role based customised experience, would that mean that we'd have to customise for each role (platform admin, platform viewer, deployments manager, and deployments viewer)? I genuinely believe this could get pretty complex and  error prone.

**Comment by ppapapetrou76** [comment]
👎 to the extract API call
👍 to leave the command labels/wording common across all targeting envs
👍 to replace the `403` or `404` with something more user-friendly 

My 2 cents but I'll leave @marclop and @karencfv make the call

**Comment by Kushmaro** [comment]
Thanks for the fix @karencfv 

> Concerns were raised about hiding commands based on host address, our documentation, the fact that our code is open sourced so users will be able to see our commands anyway and may wonder why they cannot see them.

As I've mentioned, modifying the help command was more about helping the simple user know which commands they have available for use, not about hiding anything else really.
Keep in mind that user who reads our open source isn't necessarily the user would use the cli (i'm looking more towards an administrative sort of persona rather a dev)

given this approach, I'd also prefer "Requires administrative access" rather "for ece installation only", If we look at the *majority* of the users who we intend ecctl for, they are 'simple' dev or admin users, with no admin rights, and would never have such admin rights.

internal users - should be a bit smarter than the common external user since they have some internal knowledge of the works & environments.

Which is why I personally find this path, generally less desirable.

**Comment by zanbel** [comment]
I have to leave one more comment here since :) 
Would recommend looking for inspiration in other tools you use and like, and explore how they are handling similar scenarios. This is a very common use case and aligning with commonly used CLI tool can more easily back up any proposal instead of "inventing" something new. You probably have a handy list of CLI tools you often use and have an opinion about how happy you are when using them.

**Comment by ppapapetrou76** [comment]
Folks not sure if a merged / closed PR is the best place to keep discussing about it :)

**Pull request merged**
