### PR TITLE
[docs] Update docs for getting started

### PR DESCRIPTION
**Pull request by gtback**
## Description

I just set up ecctl for the first time using this guide, and some of the example output was out of date.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation

## Readiness Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by gtback** [comment]
Another issue I found when going through this documentation, I wanted to discuss before proposing any changes (I can open a separate issue if that's better):

The [Configuring page](https://www.elastic.co/guide/en/ecctl/current/ecctl-configuring.html) talks about the precedence of configuration sources, and how to generate the config file, but doesn't explain where to get the API key that is needed for `ecctl init` ([this page](https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html) for ESS and [this section](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-restful-api-authentication.html#ece-api-keys) for ECE). It might be good to mention that above the `ecctl init` steps. For ESS we can link directly to https://cloud.elastic.co/deployment-features/keys .

I also think we'd prefer to de-emphasize the `--user` and `--pass` options (which I don't think work at all for ESS). But I didn't want to make those changes without discussing it first.

**Comment by gtback** [comment]
elasticsearch-ci is having problems. We should be able to rerun the docs once it's back up.

**Comment by alaudazzi** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by marclop — APPROVED** [review]
Thank you for the update!

**Comment by marclop** [comment]
@gtback if you can open an issue to discuss this I think that'd be the best place to do so, but all the suggestions you've made resonate with what we're doing and the where `ecctl` is today.

**Comment by alaudazzi** [comment]
@gtback thank you for testing the procedure and updating the docs!
For the [configuration page](https://github.com/elastic/ecctl/pull/502#issuecomment-902922820), would it be better to open a separate issue?

**Comment by gtback** [comment]
Thanks, @marclop and @alaudazzi! I just opened #505

**Pull request merged**
