### PR TITLE
Update ecctl user list Document.

### PR DESCRIPTION
**Pull request by taku333**
Add「Available for ECE only」message.

## Description

elastic disscuss asked the following URL.
Why can't I use "ecctl user list" in ElasticCloud? This is the question.
https://discuss.elastic.co/t/ecctl-user-list-the-requested-resource-could-not-be-found/260315

It is mentioned below that it is "Available for ECE only", but it is not in the documentation.
https://github.com/elastic/ecctl/blob/master/docs/ecctl_user_list.md

This is why I added it.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation

### CODE REVIEW

**Review by karencfv — CHANGES_REQUESTED** [review]
Thank you @taku333 for opening a docs PR :) 

On our documentation web page our `(Available for ECE only)` text that is used for the CLI `--help` flag is substituted with the ECE icon which means it is only for ECE use. So in this case no additional text is expected.

On the other hand I can see how only having an icon instead of the full text could be confusing. Let's change all of our commands that require this change to reflect that. To do that you need to change the `scripts/generate-docs.sh` file on line 43 to:

```shell
$ git diff
diff --git a/scripts/generate-docs.sh b/scripts/generate-docs.sh
index b0cc44f..d337b95 100755
--- a/scripts/generate-docs.sh
+++ b/scripts/generate-docs.sh
@@ -43,1 +43,1 @@ done
-sed -i'.bak' -e 's/(Available for ECE only)/{ece-icon}/g' ecctl*.adoc
+sed -i'.bak' -e 's/(Available for ECE only)/{ece-icon} (Available for ECE only)/g' ecctl*.adoc
```

And then run `make docs` to apply the change to all of our commands.

**Review by alaudazzi — APPROVED** [review]
LGTM for the text change :-)

**Comment by taku333** [comment]
@karencfv 
Thanks for answer!　Sorry for the late reply.

It's been a while since I've had a pull request, so I have a question.
Is there any problem if I modify "scripts/generate-docs.sh" by myself?

**Comment by karencfv** [comment]
@taku333 no worries! No problem at all, I think I didn't explain myself very well. I was asking you if, as part of this PR, you could do the following steps: 

1. Modify the `scripts/generate-docs.sh` file on line 43 to `sed -i'.bak' -e 's/(Available for ECE only)/{ece-icon} (Available for ECE only)/g' ecctl*.adoc`
2. Make sure you are in the root of the project, and run `make docs` on the terminal (this command runs the above script along with a few other checks), 
3. Commit the changes, and push them here :) 

What this will do is make sure all of the commands that require the text have it, instead of just the `ecctl user list` command, and make the build pass.

**Comment by taku333** [comment]
@karencfv 

It corresponded.
Please check with us.

**Review by karencfv — APPROVED** [review]
Looks great @taku333 🎉 Thanks a bunch for your contribution.

**Pull request merged**
