### PR TITLE
docs: change to specify that ecctl is no longer ECE specific

### PR DESCRIPTION
**Pull request by karencfv**
## Description
Documentation change to specify that ecctl is no longer ECE specific.

The docs have also been slightly modified to cater to our largest user base which will be ESS.

## Related Issues
Closes: https://github.com/elastic/ecctl/issues/161

## Motivation and Context
ESS public API launch!

## How Has This Been Tested?
n/a

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improves code quality but has no user-facing effect)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation

## Readiness Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by karencfv** [comment]
@nrichers can I also get your 👀 on this? Just to make sure this looks alright and I didn't miss anything 😄

**Comment by marclop** [comment]
Looks good but I wouldn't want to merge this until the we actually have the API serviceable to avoid misunderstandings?

**Comment by karencfv** [comment]
Thanks for the feedback @nrichers :) I am wondering if ESSP (and in the future govcloud) customers might be confused if I only list those two 🤔 would writing something like `ecctl is the CLI on steroids for the Elasticsearch Service, Elasticsearch Service Private and Elastic Cloud Enterprise APIs.` seem more appropriate for you from a writer's perspective?

cc @Kushmaro

**Comment by nrichers** [comment]
> Thanks for the feedback @nrichers :) I am wondering if ESSP (and in the future govcloud) customers might be confused if I only list those two 🤔 would writing something like `ecctl is the CLI on steroids for the Elasticsearch Service, Elasticsearch Service Private and Elastic Cloud Enterprise APIs.` seem more appropriate for you from a writer's perspective?

@karencfv I wonder if the issue isn't sidestepped by saying `Elastic Cloud product APIs` or something similar that makes it clear that we're not talking about a proper noun? Generally, simplicity is preferred.

**Comment by Kushmaro** [comment]
thanks for the note @karencfv @nrichers, I wouldn't be too worried about ESSP customers being confused since what they're getting is in fact an Elasticsearch Service operated privately.

So i'm +1 on @nrichers proposal of 
>for the Elasticsearch Service and Elastic Cloud Enterprise APIs.

**Comment by karencfv** [comment]
Thanks for the feedback @nrichers and @Kushmaro I've updated the PR :)

**Comment by karencfv** [comment]
Heya @marclop or @ppapapetrou76 can I get a ✅ from either of you so I can merge this as @Kushmaro has requested we ‘cut’ and upload the beta2 release (in the "ecctl 1.0.0-beta2 version" email)?

**Pull request merged**
